language: python
sudo: false # use container based build
notifications:
  email: false

matrix:
  include:
  - python: 2.7
    env: DEPS="numpy=1.8 scipy"
  - python: 2.7
    env: DEPS="numpy scipy numba"
  - python: 3.4
    env: DEPS="numpy scipy"
  - python: 3.5
    env: DEPS="numpy scipy"
  - python: 3.5
    env: DEPS="numpy scipy numba"

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create --yes -n test_env python=$TRAVIS_PYTHON_VERSION pytest $DEPS
  - source activate test_env
  - python setup.py install

script:
  - py.test
